#!/bin/sh

# ROUTER 2 – VXLAN MULTICAST (P2)

# Interface underlay
ip link set eth0 up
ip addr add 10.1.1.2/24 dev eth0

# Bridge L2
ip link add br0 type bridge
ip link set br0 up

# VXLAN multicast ID 10
ip link add vxlan10 type vxlan \
  id 10 \
  dev eth0 \
  group 239.1.1.1 \
  dstport 4789

ip link set vxlan10 up
ip link set vxlan10 master br0

# Interface vers le host
ip link set eth1 up
ip link set eth1 master br0
